#!/usr/bin/env zsh

# Get directory of this script
DOT_FILES=${0:a:h}

pushd $DOT_FILES

# Remove trailing '/' from directories
STOW_FOLDERS=`ls -d */ | sed "s/\///g"`

for folder in $(echo $STOW_FOLDERS)
do
	stow --verbose --target=$HOME --restow $folder
done

popd
